### ISSUE TITLE
Fix freeze upon entering SongSelectScreen.client.lua

### ISSUE THREAD

**Issue by thenerdie** [RoBeats-CS/robeats-cs#2]
I don't know what I did exactly but apparently I'm really good at breaking things -- hence why I need GitHub LOL

**Comment by ItzFireable** [comment]
It didn't freeze for me, but settings do break.

**Comment by thenerdie** [comment]
Yeah, settings is currently still under construction

**Comment by thenerdie** [comment]
I found the issue, the diff calc was calcing all map difficulties on button press lol
