### ISSUE TITLE
Controller support

### ISSUE THREAD

**Issue by Tsumuri17** [RoBeats-CS/robeats-cs#28]
This can give Xbox players a chance to to play the game with their controllers( there are many ways to play a rhythm gane like this with a controller, I don’t know how difficult it is to add controller support, but if it is added then hopefully all buttons on the Xbox controller can be used.

**Comment by Yazssuo** [comment]
This game only has keyboard play in mind, not controllers.

**Comment by astolfofangirl** [comment]
add support for itg

**Comment by thenerdie** [comment]
Yes, while I agree that this game is keyboard focused, it wouldn't hurt to add controller functionality. It would extend the playerbase quite a bit. Best of all it's not gonna be too much effort. Literally keycodes.

**Comment by thenerdie** [comment]
Added
